<?php

namespace app\admin\controller;

use think\Controller;

class Bis extends Controller
{
    private $obj;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Bis');
    }

    public function index()
    {
        $res = $this->obj->getBisByStatus(1);
        return $this->fetch('',['bis' => $res]);
    }
    public function apply()
    {
        $res = $this->obj->getBisByStatus(0);
        return $this->fetch('',['bis' => $res]);
    }
    public function dellist()
    {
        $res = $this->obj->getBisByStatus(-1);
        return $this->fetch('',['bis' => $res]);
    }
    public function edit()
    {
        $cities = model('city')->getNormalCityByParentId(0);
        $categories = model('category')->getAllFirstNormalCategorys();
        $id = input('id',0,'intval');
        $bis = $this->obj->get(['id' => $id]);
        $main = model('BisLocation')->get(['bis_id' => $id,'is_main' => '1']);
        $username = model('BisAccount')->get(['bis_id' => $id]);
        $se_cities = model('city')->getNormalCityByParentId(intval($bis['city_id']));
        $se_city_id = $this->getSeCityByCityPath(intval($bis['city_path']));
        if ($main)
        {
            $se_categories = explode(',',$main['category_path'])[1]? explode(',',$main['category_path'])[1] : '';
            $se_categories = explode('|',$se_categories);
        }
        return $this->fetch('',[
            'cities' => $cities,
            'categories' => $categories,
            'bis' => $bis,
            'main' => $main,
            'username' => $username,
            'se_cities' => $se_cities,
            'se_city_id' => $se_city_id,
            'se_categories' => $se_categories,
        ]);
    }
    public function getSeCityByCityPath($city_path)
    {
        if (empty($city_path))
        {
            return '';
        }
        if (preg_match('/,/',$city_path))
        {
            $cityArray = explode(',',$city_path);
            $cityId = $cityArray[1];
        }
        return $cityId;
    }
    //修改状态
    public function status()
    {
        $id = input('id',0,'intval');
        $status = input('status',0,'intval');
        $res_bis = $this->obj->save(['status' => $status],['id' => $id]);
        $res_location = model('BisLocation')->save(['status' => $status],['bis_id' => $id, 'is_main' => 1]);
        $res_account = model('BisAccount')->save(['status' => $status],['bis_id' => $id, 'is_main' => 1]);
        if ($res_bis && $res_location && $res_account)
        {
            $this->success('状态更新成功');
        }
        $this->error('状态更新失败');
    }
}